# Site settings Update for my Blog : spaceg.github.io Do.9.April 15.49:24 2015 Update Mo.29.Juni 00:17:28  
title: l.g
email: 838681030@qq.com
description: "您好,我的名字叫李静雅, 我来自美丽的城市南京。 "
baseurl: ""
url: "http://lucasgatsas.ch"
twitter_username: LucasGatsas
github_username:  spaceg
google_username:  https://plus.google.com/101826267816845608605/posts
instagram_username:  lucasgatsas
angelList_username:  lucas-gatsas


# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

paginate: 5 #posts per page

